INSERT INTO user (username, password, role) VALUES ('admin1', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'ADMIN');
INSERT INTO user (username, password, role) VALUES ('admin2', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'ADMIN');
INSERT INTO user (username, password, role) VALUES ('admin3', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'ADMIN');
INSERT INTO user (username, password, role) VALUES ('moderator1', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'MODERATOR');
INSERT INTO user (username, password, role) VALUES ('moderator2', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'MODERATOR');
INSERT INTO user (username, password, role) VALUES ('moderator3', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'MODERATOR');
INSERT INTO user (username, password, role) VALUES ('user1', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'USER');
INSERT INTO user (username, password, role) VALUES ('user2', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'USER');
INSERT INTO user (username, password, role) VALUES ('user3', '$2b$10$Rp8p0WpbPNP/Wyw2iZ5BoeDWUqLvHgvNgFRpstzvmm4uNuU6WJU3W', 'USER');
